[package]
name = "kupyna"
version = "0.1.0"
description = "Kupyna (DSTU 7564:2014) hash function"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2021"
documentation = "https://docs.rs/kupyna"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "hash", "kupyna"]
categories = ["cryptography", "no-std"]
rust-version = "1.71"

[dependencies]
digest = { version = "=0.11.0-pre.9", default-features = false, features = ["core-api"] }

[dev-dependencies]
hex-literal = "0.4.1"

[features]
default = ["std"]
std = ["digest/std"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
